### ISSUE TITLE
UITableView Error

### ISSUE THREAD

**Issue by williamkurniawan** [bachonk/UIImageView-Letters#18] opened 2016-02-17 11:13 UTC
![simulator screen shot feb 17 2016 6 12 32 pm](https://cloud.githubusercontent.com/assets/16736202/13107805/0fac0eea-d5a2-11e5-9fec-fae67e5108ad.png)

**Comment by bachonk** [comment] 2016-02-21 14:54
Could you post some relevant code from your `cellForRowAtIndexPath` method?

**Comment by bachonk** [comment] 2016-05-06 14:12
Closing this as cannot reproduce.

**Closed by bachonk** 2016-05-06 14:12 UTC
